---
- include_tasks: member-Debian-mjt.yml
  when:
    - samba_mjt_repository | default(false)

- include_tasks: member-Debian-disable-mjt.yml
  when:
    - not samba_mjt_repository | default(false)

- name: Install Samba Domain Controller + Member Server packages
  package:
    name:
      # optional but useful tools
      - dnsutils
      - rsync
      # Samba DC / Member Server packages list taken from:
      # http://samba.bigbird.es/doku.php?id=samba:install-samba-as-dc
      # http://samba.bigbird.es/doku.php?id=samba:install-as-member
      # (removed packages which are already dependencies of the given packages)
      - krb5-user
      - krb5-config
      - ldb-tools
      - libnss-winbind
      - libpam-winbind
      - samba
      - samba-dsdb-modules
      - samba-vfs-modules
      - smbclient
      - winbind
    state: present

- name: Install Samba files needed for AD domain provision
  package:
    name:
      - samba-ad-provision
  when:
    - samba_mjt_repository | default(false) or ansible_distribution_version|int >= 12
