---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: quay.io/centos/centos:stream8
    pre_build_image: true
  - name: debian
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
